// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::cursor_type::Cursor;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `cursor`.
///
/// Obtain a handle from the [`CursorTableAccess::cursor`] method on [`super::RemoteTables`],
/// like `ctx.db.cursor()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.cursor().on_insert(...)`.
pub struct CursorTableHandle<'ctx> {
    imp: __sdk::TableHandle<Cursor>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `cursor`.
pub struct CursorTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for CursorTableAccessor {
    type Row = Cursor;
    type Handle<'db> = CursorTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.cursor()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `cursor`.
///
/// Implemented for [`super::RemoteTables`].
pub trait CursorTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`CursorTableHandle`], which mediates access to the table `cursor`.
    fn cursor(&self) -> CursorTableHandle<'_>;
}

impl CursorTableAccess for super::RemoteTables {
    fn cursor(&self) -> CursorTableHandle<'_> {
        CursorTableHandle {
            imp: self.imp.get_table::<Cursor>("cursor"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct CursorInsertCallbackId(__sdk::CallbackId);
pub struct CursorDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for CursorTableHandle<'ctx> {
    type Row = Cursor;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Cursor> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for CursorTableHandle<'ctx> {
    type Row = Cursor;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Cursor> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = CursorInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> CursorInsertCallbackId {
        CursorInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: CursorInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = CursorDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> CursorDeleteCallbackId {
        CursorDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: CursorDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for CursorTableHandle<'ctx> {
    type InsertCallbackId = CursorInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> CursorInsertCallbackId {
        CursorInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: CursorInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for CursorTableHandle<'ctx> {
    type DeleteCallbackId = CursorDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> CursorDeleteCallbackId {
        CursorDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: CursorDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct CursorUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for CursorTableHandle<'ctx> {
    type UpdateCallbackId = CursorUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> CursorUpdateCallbackId {
        CursorUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: CursorUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for CursorTableHandle<'ctx> {
    type UpdateCallbackId = CursorUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> CursorUpdateCallbackId {
        CursorUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: CursorUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `cursor`,
/// which allows point queries on the field of the same name
/// via the [`CursorIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.cursor().id().find(...)`.
pub struct CursorIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Cursor, __sdk::Identity>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> CursorTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `cursor`.
    pub fn id(&self) -> CursorIdUnique<'ctx> {
        CursorIdUnique {
            imp: self.imp.get_unique_constraint::<__sdk::Identity>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> CursorIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &__sdk::Identity) -> Option<Cursor> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Cursor>("cursor");
    _table.add_unique_constraint::<__sdk::Identity>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<Cursor>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Cursor>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `Cursor`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait cursorQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `Cursor`.
    fn cursor(&self) -> __sdk::__query_builder::Table<Cursor>;
}

impl cursorQueryTableAccess for __sdk::QueryTableAccessor {
    fn cursor(&self) -> __sdk::__query_builder::Table<Cursor> {
        __sdk::__query_builder::Table::new("cursor")
    }
}
