// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Cursor {
    pub id: __sdk::Identity,
    pub x: f32,
    pub y: f32,
}

impl __sdk::InModule for Cursor {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Cursor`.
///
/// Provides typed access to columns for query building.
pub struct CursorCols {
    pub id: __sdk::__query_builder::Col<Cursor, __sdk::Identity>,
    pub x: __sdk::__query_builder::Col<Cursor, f32>,
    pub y: __sdk::__query_builder::Col<Cursor, f32>,
}

impl __sdk::__query_builder::HasCols for Cursor {
    type Cols = CursorCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        CursorCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            x: __sdk::__query_builder::Col::new(table_name, "x"),
            y: __sdk::__query_builder::Col::new(table_name, "y"),
        }
    }
}

/// Indexed column accessor struct for the table `Cursor`.
///
/// Provides typed access to indexed columns for query building.
pub struct CursorIxCols {
    pub id: __sdk::__query_builder::IxCol<Cursor, __sdk::Identity>,
}

impl __sdk::__query_builder::HasIxCols for Cursor {
    type IxCols = CursorIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        CursorIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Cursor {}
