// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SetCursorPositionArgs {
    pub x: f32,
    pub y: f32,
}

impl From<SetCursorPositionArgs> for super::Reducer {
    fn from(args: SetCursorPositionArgs) -> Self {
        Self::SetCursorPosition {
            x: args.x,
            y: args.y,
        }
    }
}

impl __sdk::InModule for SetCursorPositionArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `set_cursor_position`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait set_cursor_position {
    /// Request that the remote module invoke the reducer `set_cursor_position` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`set_cursor_position:set_cursor_position_then`] to run a callback after the reducer completes.
    fn set_cursor_position(&self, x: f32, y: f32) -> __sdk::Result<()> {
        self.set_cursor_position_then(x, y, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `set_cursor_position` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn set_cursor_position_then(
        &self,
        x: f32,
        y: f32,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()>;
}

impl set_cursor_position for super::RemoteReducers {
    fn set_cursor_position_then(
        &self,
        x: f32,
        y: f32,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(SetCursorPositionArgs { x, y }, callback)
    }
}
